[tool.poetry]
name = "rdrama"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "AGPL"
package-mode = false

[tool.poetry.dependencies]
python = "~3.13"
beautifulsoup4 = "*"
bleach = "*"
tinycss2 = "*"
Flask = "*"
Flask-Caching = "*"
Flask-Compress = "*"
Flask-Limiter = "2.*"
Flask-Mail = "*"
Flask-Migrate = "*"
Flask-Socketio = "*"
flask_profiler = "*"
gunicorn = "*"
eventlet = "*"
lxml = "*"
mistletoe = "*"
matplotlib = "*"
Pillow = "*"
psutil = "*"
pyotp = "*"
python-dotenv = "*"
qrcode = "*"
redis = "*"
requests = "*"
SQLAlchemy = "*"
user-agents = "*"
psycopg2 = "*"
pusher_push_notifications = "*"
yattag = "*"
webptools = "*"
supervisor = "*"
superlance = "*"
alive-progress = "*"
setuptools = "*"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
tabulate = "*"
pandas = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
norecursedirs = [
    "thirdparty/*",
]

[tool.coverage.run]
source = ["files"]
omit = [
    "*/tests/*",
    "*/test_*.py",
    "*/__pycache__/*",
    "*/migrations/*",
    "*/thirdparty/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "if typing.TYPE_CHECKING:",
]
skip_covered = false
show_missing = true
precision = 2

[tool.coverage.html]
directory = "htmlcov"
