INSERT INTO public.users (username, passhash, created_utc, admin_level, over_18, is_activated, bio, bio_html, login_nonce, is_private,
	unban_utc, original_username, customtitle, defaultsorting, defaultsortingcomments, defaulttime, namecolor, titlecolor,
	customtitleplain, theme, themecolor, changelogsub, reddit, css, profilecss, coins, agendaposter,
	post_count, comment_count, background, verified, truecoins, cardview
) VALUES ('System', '', extract(epoch from now()), 0, true, true, '', '', 0, false, 
			0, 'System', '', 'hot', 'top', 'day', 'ff66ac', 'ff66ac',
			'', 'dark', 'ff66ac', false, 'old.reddit.com', '', '', 0, 0,
			0, 0, '', 'Verified', 0, false),
		 ('AutoJanny', '', extract(epoch from now()), 0, true, true, '', '', 0, false, 
			0, 'AutoJanny', '', 'hot', 'top', 'day', 'ff66ac', 'ff66ac',
			'', 'dark', 'ff66ac', false, 'old.reddit.com', '', '', 0, 0,
			0, 0, '', 'Verified', 0, false),
		 ('Snappy', '', extract(epoch from now()), 0, true, true, '', '', 0, false, 
			0, 'Snappy', '', 'hot', 'top', 'day', '62ca56', 'e4432d',
			'', 'dark', '30409f', false, 'old.reddit.com', '', '', 0, 0,
			0, 0, '', 'Verified', 0, false),
		 ('longpostbot', '', extract(epoch from now()), 0, true, true, '', '', 0, false, 
			0, 'longpostbot', '', 'hot', 'top', 'day', '62ca56', 'e4432d',
			'', 'dark', '30409f', false, 'old.reddit.com', '', '', 0, 0,
			0, 0, '', 'Verified', 0, false),
		 ('zozbot', '', extract(epoch from now()), 0, true, true, '', '', 0, false, 
			0, 'zozbot', '', 'hot', 'top', 'day', '62ca56', 'e4432d',
			'', 'dark', '30409f', false, 'old.reddit.com', '', '', 0, 0,
			0, 0, '', 'Verified', 0, false),
		 ('AutoPoller', '', extract(epoch from now()), 0, true, true, '', '', 0, false, 
			0, 'AutoPoller', '', 'hot', 'top', 'day', '62ca56', 'e4432d',
			'', 'dark', '30409f', false, 'old.reddit.com', '', '', 0, 0,
			0, 0, '', 'Verified', 0, false),
		 ('AutoBetter', '', extract(epoch from now()), 0, true, true, '', '', 0, false, 
			0, 'AutoBetter', '', 'hot', 'top', 'day', '62ca56', 'e4432d',
			'', 'dark', '30409f', false, 'old.reddit.com', '', '', 0, 0,
			0, 0, '', 'Verified', 0, false),
		 ('AutoChoice', '', extract(epoch from now()), 0, true, true, '', '', 0, false, 
			0, 'AutoChoice', '', 'hot', 'top', 'day', '62ca56', 'e4432d',
			'', 'dark', '30409f', false, 'old.reddit.com', '', '', 0, 0,
			0, 0, '', 'Verified', 0, false);

INSERT INTO public.badge_defs VALUES
(1,'Alpha User','Joined during open alpha'),
(2,'Verified Email','Verified Email'),
(3,'Code Contributor','Contributed to the site''s source code'),
(4,'White Hat','Responsibly reported a security issue'),
(6,'Beta User','Joined during open beta'),
(7,'Bug Chaser','Found a bug'),
(10,'Bronze Recruiter','Recruited 1 friend to join the site'),
(11,'Silver Recruiter','Recruited 10 friends to join the site'),
(12,'Gold Recruiter','Recruited 100 friends to join the site'),
(15,'Idea Maker','Had a good idea for the site which was implemented by the developers'),
(16,'Marsey Master','Contributed 10 (or more!!!!) Marsey emojis ✨'),
(17,'Marsey Artisan','Contributed a Marsey emoji ✨'),
(18,'Artisan','Contributed to site artwork'),
(21,'Paypig','Contributed at least $5'),
(22,'Renthog','Contributed at least $10'),
(23,'Landchad','Contributed at least $20'),
(24,'Terminally online turboautist','Contributed at least $50'),
(25,'Marsey''s Sugar Daddy','Contributed at least $100'),
(26,'JIDF Bankroller','Contributed at least $250'),
(27,'Rich Bich','Contributed at least $500'),
(28,'Chud','Forced to use the chud theme'),
(59,'Lolcow','Beautiful and valid milk provider'),
(60,'Unironically Retarded','Demonstrated a wholesale inability to read the room'),
(61,'Lab Rat','Helped test features in development'),
(62,'Master Baiter','For outstanding achievement in the field of catching fish'),
(63,'Balls','I wrote carp on my balls as a sign of submission'),
(64,'The Other Kind Of Good Journalist','Contributed positive media attention to the site'),
(65,'2021 Spooooooky Marsey Artist','Contributed a VERY SCARY Marsey for Halloween 2021!'),
(66,'Sk8r Boi','Certifies that this user is NOT a poser'),
(67,'Unpausable','Spent 40,000 coins on an unpausable profile anthem'),
(68,'Pause Button','Spent 20,000 coins on a profile anthem pause button'),
(69,'Little Big Spender','Dropped 10,000 coins at the shop'),
(70,'Big Spender','Dropped 100,000 coins at the shop'),
(71,'Big Big Spender','Dropped 250,000 coins at the shop'),
(72,'Big Big Big Spender','Dropped 500,000 coins at the shop'),
(73,'Le Rich Gentlesir','Spent a fucking million coins at the shop'),
(74,'Grass Toucher','Awarded for molesting plant life'),
(75,'Halloween 21','Awarded for surviving Homoween 2021'),
(76,'Low Roller','Bought 10 lootboxes'),
(77,'Middle Roller','Bought 50 lootboxes'),
(78,'High Roller','Bought 150 lootboxes'),
(79,'Merchant','Contributed a new line of product to Marsey''s Coin Emporium'),
(80,'Artist Laureate',''),
(81,'Patron of the Arts','Sponsored the creation of an approved Marsey'),
(83,'All-Seeing Eye','Can view private profiles'),
(84,'Alt-Seeing Eye','Can see alts'),
(85,'Sigma User',''),
(86,'Holly Jolly Marsey Artist','Contributed a VERY JOLLY Marsey for Christmas 2021!'),
(87,'Unblockable','This user is unblockable'),
(88,'Provider','This user provided a bountiful feast for Thanksgiving'),
(89,'Dinner','Yes, it is edible'),
(90,'Fish','This user cannot be unfollowed'),
(91,'Grinch','This user is a joyless grinch who pays money to avoid having fun'),
(92,'NFT Artist','Drew a marsey that was used as an NFT'),
(93,'NFT Owner','Bought a marsey NFT'),
(94,'Progressive Stack Award','Upvotes/downvotes on this user''s posts and comments have double the ranking effect'),
(95,'Bird Site Award','This user is limited to 140 characters'),
(96,'Flairlock Award','This user''s flair has been locked by someone else'),
(97,'Pizzashill Award','This user has to make their posts and comments more than 280 characters'),
(98,'Marsey Award','This user is limited to posting marseys'),
(99,'Sidebar Artist','Contributed artwork featured on the sidebar'),
(100,'True Believer','This user sees through communist lies'),
(101,'Banner Artist','Contributed a banner image to the site'),
(102,'Christmas 21','Awarded for surviving Fistmas 2021'),
(103,'Benefactor','Gave the Benefactor award to someone'),
(104,'BADASS OUTLAW','Bad boy who does not play by the rules'),
(105,'SCAM','lmao get fucked retard');