"""empty message

Revision ID: 000000000000
Revises: 
Create Date: 2022-05-12 01:29:23.308615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'oauth_apps', ['app_id'], ['id'])
    op.create_foreign_key(None, 'commentvotes', 'oauth_apps', ['app_id'], ['id'])
    op.create_foreign_key(None, 'modactions', 'users', ['user_id'], ['id'])
    op.drop_constraint('unique_id', 'oauth_apps', type_='unique')
    op.add_column('submissions', sa.Column('bump_utc', sa.Integer(), server_default=FetchedValue(), nullable=True))
    op.create_foreign_key(None, 'submissions', 'oauth_apps', ['app_id'], ['id'])
    op.drop_constraint('one_banner', 'users', type_='unique')
    op.drop_constraint('one_discord_account', 'users', type_='unique')
    op.drop_constraint('uid_unique', 'users', type_='unique')
    op.drop_constraint('users_original_username_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_foreign_key(None, 'votes', 'oauth_apps', ['app_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_original_username_key', 'users', ['original_username'])
    op.create_unique_constraint('uid_unique', 'users', ['id'])
    op.create_unique_constraint('one_discord_account', 'users', ['discord_id'])
    op.create_unique_constraint('one_banner', 'users', ['bannerurl'])
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'bump_utc')
    op.create_unique_constraint('unique_id', 'oauth_apps', ['client_id'])
    op.drop_constraint(None, 'modactions', type_='foreignkey')
    op.drop_constraint(None, 'commentvotes', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
