"""remove many user award tracking columns

Revision ID: 0d4c7cf3da6d
Revises: 61c6f838c5c6
Create Date: 2022-11-07 08:04:52.285019+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4c7cf3da6d'
down_revision = '61c6f838c5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alt')
    op.drop_column('users', 'unblockable')
    op.drop_column('users', 'deflector')
    op.drop_column('users', 'bird')
    op.drop_column('users', 'rehab')
    op.drop_column('users', 'fish')
    op.drop_column('users', 'mute')
    op.drop_column('users', 'eye')
    op.drop_column('users', 'longpost')
    op.drop_column('users', 'marseyawarded')
    op.drop_column('users', 'progressivestack')
    op.drop_column('users', 'unmutable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unmutable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('progressivestack', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('marseyawarded', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('longpost', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('eye', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('mute', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('fish', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('rehab', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bird', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('deflector', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('unblockable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('alt', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
