"""Remove treasure_amount from comments.

Revision ID: c217c608d86c
Revises: c5bbdae9a233
Create Date: 2022-09-04 21:49:42.471406+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c217c608d86c'
down_revision = 'c5bbdae9a233'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('comments', 'treasure_amount')
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('comments', sa.Column('treasure_amount', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
	# ### end Alembic commands ###
