"""update db to match models at fork time

Revision ID: 4a1f7859151b
Revises: 0aef77162269
Create Date: 2022-05-12 03:08:32.417479+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1f7859151b'
down_revision = '0aef77162269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'oauth_apps', ['app_id'], ['id'])
    op.create_foreign_key(None, 'commentvotes', 'oauth_apps', ['app_id'], ['id'])
    op.create_foreign_key(None, 'modactions', 'users', ['user_id'], ['id'])
    op.add_column('submissions', sa.Column('bump_utc', sa.Integer(), server_default=FetchedValue(), nullable=True))
    op.create_foreign_key(None, 'submissions', 'oauth_apps', ['app_id'], ['id'])
    op.create_foreign_key(None, 'votes', 'oauth_apps', ['app_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'bump_utc')
    op.drop_constraint(None, 'modactions', type_='foreignkey')
    op.drop_constraint(None, 'commentvotes', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
