"""changes to volunteer_janitor behavior

Revision ID: e2cd2818a196
Revises: 65ce80ffc30e
Create Date: 2022-11-20 10:10:48.464867+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2cd2818a196'
down_revision = '65ce80ffc30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_janitor', sa.Column('recorded_utc', sa.DateTime(), nullable=False))
    op.drop_column('volunteer_janitor', 'edited_utc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_janitor', sa.Column('edited_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('volunteer_janitor', 'recorded_utc')
    # ### end Alembic commands ###
