"""Change created_utc to datetimez for flags

Revision ID: bdb4b7a2e88b
Revises: 5195118d6a51
Create Date: 2023-07-22 03:05:16.984823+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb4b7a2e88b'
down_revision = '5195118d6a51'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
