"""Move 'deleted_utc' into 'state_user_deleted_utc'.

Revision ID: 8337558f4f36
Revises: 6403c9151c12
Create Date: 2023-06-11 09:09:00.235602+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8337558f4f36'
down_revision = '6403c9151c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('state_user_deleted_utc', sa.DateTime(), nullable=True))
    op.drop_column('comments', 'deleted_utc')
    op.add_column('submissions', sa.Column('state_user_deleted_utc', sa.DateTime(), nullable=True))
    op.drop_index('subimssion_binary_group_idx', table_name='submissions')
    op.create_index('subimssion_binary_group_idx', 'submissions', ['is_banned', 'state_user_deleted_utc', 'over_18'], unique=False)
    op.drop_index('submission_isdeleted_idx', table_name='submissions')
    op.create_index('submission_isdeleted_idx', 'submissions', ['state_user_deleted_utc'], unique=False)
    op.drop_index('submission_new_sort_idx', table_name='submissions')
    op.create_index('submission_new_sort_idx', 'submissions', ['is_banned', 'state_user_deleted_utc', sa.text('created_utc DESC'), 'over_18'], unique=False)
    op.drop_column('submissions', 'deleted_utc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('deleted_utc', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index('submission_new_sort_idx', table_name='submissions')
    op.create_index('submission_new_sort_idx', 'submissions', ['is_banned', 'deleted_utc', 'created_utc', 'over_18'], unique=False)
    op.drop_index('submission_isdeleted_idx', table_name='submissions')
    op.create_index('submission_isdeleted_idx', 'submissions', ['deleted_utc'], unique=False)
    op.drop_index('subimssion_binary_group_idx', table_name='submissions')
    op.create_index('subimssion_binary_group_idx', 'submissions', ['is_banned', 'deleted_utc', 'over_18'], unique=False)
    op.drop_column('submissions', 'state_user_deleted_utc')
    op.add_column('comments', sa.Column('deleted_utc', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('comments', 'state_user_deleted_utc')
    # ### end Alembic commands ###
