"""Add quote index to optimize chat item deletion

Revision ID: a2fce4808e1d
Revises: 850c47d647ba
Create Date: 2023-08-27 16:47:31.490361+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2fce4808e1d'
down_revision = '850c47d647ba'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.create_index('quote_index', 'chat_message', ['quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('quote_index', table_name='chat_message')
    # ### end Alembic commands ###
