"""DDL: add comments.descendant_count column

Revision ID: f8ba0e88ddd1
Revises: e2cd2818a196
Create Date: 2023-01-03 07:49:32.295633+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ba0e88ddd1'
down_revision = 'e2cd2818a196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column(
		'descendant_count',
		sa.Integer(),
		nullable=False,
		server_default=sa.text('0')
	))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'descendant_count')
    # ### end Alembic commands ###
