"""Add index on comments.top_comment_id

Revision ID: 2481e3a04265
Revises: 3023741ec9dd
Create Date: 2026-02-27 03:40:20.761500+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2481e3a04265'
down_revision = '3023741ec9dd'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('comment_top_comment_id_index', ['top_comment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('comment_top_comment_id_index')

    # ### end Alembic commands ###
