name: "E2ETests"

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        ./util/test.py
